---
- name: Deploy Web App
  hosts: 3.110.105.142 
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy HTML to web server
      copy:
        src: ../app/
        dest: /var/www/html/
